### PR TITLE
Add __XTENSA__ to target.h

### PR DESCRIPTION
**Pull request by coder0xff**

### CODE REVIEW

**Comment by coder0xff** [comment]
Hi. Would you trigger the workflow please?

**Comment by coder0xff** [comment]
@briansmith Is it safe to assume that the ci / deny failure is unrelated?

**Comment by briansmith** [comment]
Please:
1. Make a mk/install-build-tools-unsupported.sh that is in the same form of mk/install-build-tools.sh, which adds support for installing the xtensa toolchain on an Ubuntu system, starting from the state where qemu-xtensa is not installed.
2. Make a mk/cargo-unsupported.sh that mirrors mk/cargo.sh which uses the xtensa toolchain to run cargo commands in qemu-xtensa.
3. Update .github/workflows/ci.yml to add the xtensa target to the test matrix.

**Comment by briansmith** [comment]
Instead of continuing to grow this allowlist, I'd rather eliminate it. Please help with implementing the strategy in https://github.com/briansmith/ring/pull/2042#issuecomment-2120898907 if you can.

**Pull request closed without merging**
