### PR TITLE
Use slice::iter

### PR DESCRIPTION
**Pull request by lzutao**
See clippy::into_iter lint and https://github.com/rust-lang/rust/pull/65819

### CODE REVIEW

**Comment by LukasKalbertodt** [comment]
The CI error doesn't seem to have anything to do with this change. Instead, [this Rust PR](https://github.com/rust-lang/rust/pull/65294) is likely relevant.

**Comment by briansmith** [comment]
Thanks!

**Comment by LukasKalbertodt** [comment]
@briansmith Thanks for merging! Do you think you could release this as `0.16.10`?

**Comment by briansmith** [comment]
> @briansmith Thanks for merging! Do you think you could release this as `0.16.10`?

I plan to do a release in early January.

**Comment by LukasKalbertodt** [comment]
@briansmith I hope I'm not too annoying, but do you think you could release this soonish? :)

**Pull request merged**
