### PR TITLE
Migrate PBKDF2 iteration count from `usize` to `u32`.

### PR DESCRIPTION
**Pull request by frewsxcv**
https://github.com/briansmith/ring/issues/38

I agree to license my contributions to each file under the terms given
at the top of each file I changed.

### CODE REVIEW

**Comment by frewsxcv** [comment]
Regarding https://github.com/briansmith/ring/issues/38, I glanced at other `usize` uses in *ring* and nothing else stuck out to me.

**Comment by briansmith** [comment]
This looks good to me, but I'm going to wait until 0.7.0 to merge this since it's an API change.

**Comment by frewsxcv** [comment]
Sounds good!

**Comment by briansmith** [comment]
Landed as 8a655e45fc0e7926db3932677a82e875bc559ce6 in master. Thanks!

**Pull request closed without merging**
