### PR TITLE
Adding AES_GCM_SIV implementation to Ring rust library

### PR DESCRIPTION
**Pull request by misnomer1**
I agree to license my contributions to each file under the terms given
at the top of each file I changed.

### CODE REVIEW

**Comment by misnomer1** [comment]
Note this commit contains both ASM and non-ASM impl of AES_GCM_SIV

**Comment by briansmith** [comment]
Thanks!

Just FYI, I canceled the CI job for this PR because I need to clear up the CI for some more urgent changes. However, that doesn't mean that I don't like your PR. I am excited about adding the feature and I hope to have some time to review this PR soon.

**Comment by misnomer1** [comment]
Sure, thank you for the response. It would be great if you can get to this PR soon

**Comment by briansmith** [comment]
I will need to merge the rest of the unmerged BoringSSL changes so that we're even with the current BoringSSL master before I can look at this. I expect many changes will be needed since the AES and GCM code got totally rewritten.

**Comment by briansmith** [comment]
Closing this because it's very out of date now and I'm about to delete the master branch.

**Pull request closed without merging**
