### PR TITLE
Implement RSA signing in Rust.

### PR DESCRIPTION
**Pull request by briansmith**

### CODE REVIEW

**Comment by briansmith** [comment]
@ranweiler I'm curious if I've got the terminology right this time in f684da8c0acb5e65cff88249edba4fc26d3e0d27. Let me know if you see something wrong or that can otherwise be improved (disregarding the copyright line typo.)

**Comment by ranweiler** [comment]
@briansmith looks good overall, I suggested some minor tweaks.

**Comment by briansmith** [comment]
@ranweiler Thanks for looking at that (busted) commit! I fixed the wording issues you mentioned and hopefully I didn't introduce new ones.

**Comment by briansmith** [comment]
Landed as:

dabde0286ff2fec7875556731c45ba7c135587c1 Use standard names for RSA private key fields.
7dcaddfaba03df2877bce347bfcbe445da39195a Give `GFp_*` modular arithmetic primitives more general names.
6822329083fee789dc5d64750b0d3745d47b62fb Use `limb_` and `limbs_` instead of `gfp_` for low-level limb ops.
1b07946eff33806495eab0fb4777fd2bc1d12552 Restore `GFp_BN_mod_add_quick` and use it in RSA CRT.
13a77c9926ff5b49bb551372a259c8d8556d5364 Use `GFp_BN_ucmp` instead of `GFp_BN_cmp` in `ring::rsa::bigint`.
9ecabeb700147d1170e4c05dce12fc75906fdff8 Don't call the integers modulo the composite public modulus `Field`s.
1dee59d7119193ca73ec848900b9ad2dba3a44c5 Clarify README.
aae0a36c2d672b95635baac64874bb1e546dc649 Update the creation myth in README.md.
368279ffd2828b8846fb6d3eb5ea193af83a3abb Implement RSA signing using the CRT using Rust.

**Pull request closed without merging**
