### PR TITLE
Replace usages of `ROTR` macro with `rotate_right_u64`.

### PR DESCRIPTION
**Pull request by frewsxcv**
I agree to license my contributions to each file under the same terms
given at the top of each file I changed.

### CODE REVIEW

**Comment by briansmith** [comment]
There's no performance difference on MSVC, so no intrinsics seem necessary, at least for that compiler.

**Comment by frewsxcv** [comment]
Fairly big performance regression with GCC

https://gist.github.com/frewsxcv/4459dd9e7cdc78f5edb2

**Comment by frewsxcv** [comment]
Actually, I think that's Clang, not GCC. For whatever reason, Apple aliases `gcc` to `clang`

**Comment by briansmith** [comment]
Older verisons of clang haad some trouble optimizing things like this. What version of clang are you using?

**Comment by frewsxcv** [comment]
Similar results for gcc-4.9: https://gist.github.com/frewsxcv/4459dd9e7cdc78f5edb2

> What version of clang are you using?

```
coreyf@frewbook-pro ~/D/c/ring (master) [130]> clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```

**Comment by frewsxcv** [comment]
Just realized I was running master without `OPENSSL_NO_ASM`. Here are number with `OPENSSL_NO_ASM=1` for all runs: https://gist.github.com/frewsxcv/502ef3886c71532d8a5d

**Comment by briansmith** [comment]
Thanks! Committed as 13060ab6f1c52989804d7c9b3f1904c4cdf13ede. Note that I reduced the indentation of the function to two spaces (it was four spaces) and renamed `data` to `x`.

**Pull request closed without merging**
