### PR TITLE
Update directory structure

### PR DESCRIPTION
**Pull request by cramertj**
This PR moves around several files in order to
remove #![allow(legacy_directory_ownership)].
This will prevent breakage when the
legacy_directory_ownership warning becomes a hard
error.

cc https://github.com/briansmith/ring/issues/598

### CODE REVIEW

**Comment by briansmith** [comment]
Instead of doing renames like src/aead/aead.rs → src/aead/mod.rs, please do renames like src/aead/aead.rs → src/aead.rs, using the new path rules.

**Comment by cramertj** [comment]
@briansmith Oh, so you'd like to enable `#![feature(non_modrs_mods)]`?

**Comment by briansmith** [comment]
> @briansmith Oh, so you'd like to enable #![feature(non_modrs_mods)]?

Sure, but the code needs to work in Stable Rust too. It sounds like the rustc developers need to come up with a migration plan.

**Comment by cramertj** [comment]
@briansmith If you want this to work in stable rust, the only way to structure it is the way I have here.

**Comment by Fuzen-py** [comment]
@cramertj You can always just move it to the way it was requested and then add a mod.rs to make what should be public public. Id say it would seem even messier though

**Comment by jbg** [comment]
> It sounds like the rustc developers need to come up with a migration plan.

They did. If you disagree with it, this doesn't seem like the most productive way to indicate that, considering that ignoring the warnings that you weren't following the plan has broken `ring` for anyone who tracks rust nightly.

**Comment by briansmith** [comment]
I went ahead and locked this thread to minimize wasted effort on everybody's part. There's a large number of pending changes to *ring* that I want to merge before I rename any files. I'll try to get all these changes done by the end of January.

**Comment by briansmith** [comment]
The issue that this PR addresses was fixed in the 0.13.0-alpha release. Closing this.

**Pull request closed without merging**
