### PR TITLE
Use /dev/urandom for SecureRandom on Redox

### PR DESCRIPTION
**Pull request by jackpot51**
This fixes builds on Redox.

### CODE REVIEW

**Comment by briansmith** [comment]
Thanks!

**Comment by jackpot51** [comment]
Thank you! How can I tell when you do a new release with this included?

**Comment by briansmith** [comment]
> Thank you! How can I tell when you do a new release with this included?

I am expecting to do a new release in the next couple weeks. There will be a PR with a title like "0.17.0" or so when that happens.

**Comment by jackpot51** [comment]
Great!

**Pull request merged**
