### PR TITLE
Replace usages of `HOST_c2l` macro with `from_be_u32` function

### PR DESCRIPTION
**Pull request by frewsxcv**
https://github.com/briansmith/ring/issues/71

I agree to license my contributions to each file under the same terms
given at the top of each file I changed.

### CODE REVIEW

**Comment by frewsxcv** [comment]
@briansmith This is my first time using C since university, so please forgive me if I'm doing anything blatantly wrong :stuck_out_tongue:

**Comment by frewsxcv** [comment]
I'm out right now and will address the issues you brought up later. Thanks for all the suggestions! Much appreciated :)

**Comment by briansmith** [comment]
>> If we run into performance problems,
> Did you mean to finish this thought?

If we run into performance problems, we can explore using the built-in intrinsic functions, but I'd like `_byteswap_uint64`/`_byteswap_ulong` and the GCC/clang equivalents, but I'd like to avoid all inline assembly if at all possible, and I'd like to avoid `_byteswap_uint64`/`_byteswap_ulong` and friends if posssible.

**Comment by frewsxcv** [comment]
Intentionally made a new commit so you could see the changes easier. I figure a `git squash` will happen later.

Thanks again for walking me through some of this, I really appreciate it!

Let me know how the latest changes look

**Comment by frewsxcv** [comment]
Addressed your comments.

**Comment by frewsxcv** [comment]
Ran crypto-bench on this: https://gist.github.com/frewsxcv/5acf2a5a6f4e112a9421

**Comment by briansmith** [comment]
When working on stuff related to this, I realized another issue: It will eventually be better to have two versions of `from_be_u32`: One that takes a `const uint8_t *` like the current one does, and one that takes a `uint32_t` (not a pointer). The name `from_be_u32` makes more sense for the non-pointer variant. Because of that, I'm going to  rename `from_be_u32` to `from_be_u32_ptr`.

**Comment by frewsxcv** [comment]
>Because of that, I'm going to rename from_be_u32 to from_be_u32_ptr.

SGTM :+1:

**Comment by frewsxcv** [comment]
Merged in as https://github.com/briansmith/ring/commit/16af088fbc2099d3b03e04b8086278cdf03104e1

**Comment by briansmith** [comment]
See the discussion in #71 about the follow-up to address potentially-undefined behavior and performance regressions.

**Comment by briansmith** [comment]
Thanks again!

**Pull request closed without merging**
