### PR TITLE
Hacks taken from @amock to make RISC-V build.

### PR DESCRIPTION
**Pull request by xfbs**
As stated in #1419, trying to get RISC-V to build. This uses generic C code for montomery multiplication taken from @amock. But it builds and tests successfully like this.

### CODE REVIEW

**Comment by briansmith** [comment]
Thanks for the PR! Could you rebase this on top of #1558? I think we just need the base.h changes now.

**Comment by briansmith** [comment]
Also, could you add the changes to the scripts in mk/ to get `cargo.sh test` working for some RISC-V targets in QEMU? This will enable us to more easily work on adding RISC-V-specific code paths in the future.

**Comment by olof-nord** [comment]
This PR allows me to build ring locally, thanks!
But with this branch several years old, it is 442 commits behind :)

It would be fantastic to get this working on riscv - for example to run lemmy on riscv hardware.

I understand the generic approach suggested there, I will keep my eyes open for updates!
https://github.com/briansmith/ring/issues/1455

**Comment by briansmith** [comment]
Thanks. For now I'm planning to go with the simpler PR #1627. If you want, we can revisit the extended changes you have here, afterward.

**Pull request closed without merging**
