### PR TITLE
Use clang on travis with Android

### PR DESCRIPTION
**Pull request by tomaka**
Follow-up of #633

### CODE REVIEW

**Comment by tomaka** [comment]
The travis failure is due to the fact that the inline assembly uses thumb-2 instructions.

According to [this page](https://developer.android.com/ndk/guides/standalone_toolchain#clang_targets_with_arm), we are supposed to use the `thumb-` targets, which makes sense to me.

I'm not sure why it works for gcc, but I suppose that gcc doesn't follow the same system.
I'm also confused as to how Parity successfully compiles despite the fact that is uses clang and [a git version of ring](https://github.com/paritytech/ring/) (so no precompiled header).

**Comment by briansmith** [comment]
> According to this page, we are supposed to use the thumb- targets, which makes sense to me.

Let's change this PR to use the thumb targets so the CI build step passes.

**Comment by briansmith** [comment]
> Let's change this PR to use the thumb targets so the CI build step passes.

Never mind,I don't think that's the right solution. I think I have a fix. Working on it.

**Comment by briansmith** [comment]
> I'm also confused as to how Parity successfully compiles despite the fact that is uses clang and [...]

I bet Parity is using a newer version of the NDK and/or clang or whatever and I bet that is the solution here. Any tips on how to get *ring*'s CI to work more like Parity's?

**Comment by tomaka** [comment]
Tests seem to pass on travis :tada:

**Pull request merged**
