### PR TITLE
Rename *ring* internals to avoid conflicts with OpenSSL.

### PR DESCRIPTION
**Pull request by briansmith**
This series of commits will rename every single extern C symbol in *ring* so that each one has a different name from any OpenSSL function. This should allow *ring* and rust-openssl to be linked together into the same program.

### CODE REVIEW

**Comment by briansmith** [comment]
Just to clarify: This is a WIP. It isn't done yet. I'll keep updating the PR as I make progress.

**Comment by briansmith** [comment]
Landed in master as:

fcbf905 Use the GFp_ prefix for nistz384 externs.
c378a2e Use the GFp_ prefix for nistz256 externs.
dd0865a Use the GFp_ prefix for digest externs.
02602de Use the "GFp_" prefix C integer type metrics & simplify them.
e6b9b97 Use the "GFp_" prefix for Curve25519 functions.
7900e98 Use the "GFp_" prefix for RSA externs.
5ec28f5 Use the "GFp_" prefix for ChaCha20 externs.
05f2c83 Use the "GFp_" prefix for poly1305 functions.
5eb9ac9 Use the "GFp_" prefix for CPU capabilities externs.
e95806f Use the "GFp_" prefix for BIGNUM externs.
6c8a344 Use the "GFp_" prefix for AES externs.

**Comment by frewsxcv** [comment]
Can this be closed?

**Comment by briansmith** [comment]
I'm going to leave this open because (a) I didn't verify it is correct on every target, especially no-asm, ARM32, AAarch64, and (b) I want to add something to the build/test automation to ensure there are no regressions in this.

**Comment by briansmith** [comment]
> I'm going to leave this open because (a) I didn't verify it is correct on every target, especially no-asm, ARM32, AAarch64, and (b) I want to add something to the build/test automation to ensure there are no regressions in this.

The remaining work is now tracked in #297.

**Pull request closed without merging**
