### PR TITLE
build.rs: Clarify `package` logic after aarch64-pc-windows-msvc support was added.

### PR DESCRIPTION
**Pull request by briansmith**
See the commit messages of the individual commits for details on each change.

### CODE REVIEW

**Comment by briansmith** [comment]
@Alovchin91 @awakecoding Could you please review these changes? It's probably easiest & best to review each commit individually.

**Review by awakecoding — APPROVED** [review]
LGTM. it's nice to make it less nasm-specific!

**Review by Alovchin91 — APPROVED** [review]
LGTM

**Comment by briansmith** [comment]
@@Alovchin91 @awakecoding Thanks!

**Pull request merged**
