### PR TITLE
Faster montgomery setup

### PR DESCRIPTION
**Pull request by briansmith**
This is a sketch of a possible fix for #431. See the last commit in this series. Unfortunately, it gets messier moduli with lengths that aren't of the form 2<sup>2<sup>n</sup></sup>. Fortunately, most common moduli lengths (1024, 2048, 4096, and 8192) are of that form, but 3072 isn't. We may add a special case for 3072.

@ctz @DemiMarie Can you run your benchmarks against this and let me know the results?

### CODE REVIEW

**Comment by briansmith** [comment]
OK, maybe the special case for 3072-bit moduli isn't that difficult. I added a sketch of it to this PR.

**Comment by ctz** [comment]
> @ctz @DemiMarie Can you run your benchmarks against this and let me know the results?

Sorry it took so long to get to this. Before (ring at b141727, release build):

```
verify_server_cert(github): min 520us
verify_server_cert(google): min 532us
verify_server_cert(duckduckgo): min 521us
verify_server_cert(reddit): min 529us
verify_server_cert(arstechnica): min 1342us
verify_server_cert(stackoverflow): min 525us
verify_server_cert(hn): min 1364us
verify_server_cert(servo): min 1018us
verify_server_cert(rustlang): min 1378us
verify_server_cert(twitter): min 521us
verify_server_cert(wapo): min 517us
verify_server_cert(wikipedia): min 517us
```

After (ring at 8aed4d1):

```
verify_server_cert(duckduckgo): min 89us
verify_server_cert(github): min 90us
verify_server_cert(google): min 88us
verify_server_cert(reddit): min 89us
verify_server_cert(arstechnica): min 202us
verify_server_cert(hn): min 196us
verify_server_cert(rustlang): min 195us
verify_server_cert(twitter): min 88us
verify_server_cert(stackoverflow): min 88us
verify_server_cert(wapo): min 87us
verify_server_cert(wikipedia): min 83us
verify_server_cert(servo): min 928us
```

So that's a fantastic improvement! 👍 

The regressing case (servo.org) is a secp256 -> secp256 -> secp384 chain.

**Comment by briansmith** [comment]
Obsoleted by #513.

**Comment by briansmith** [comment]
@ctz Thanks for testing this. Regarding the P-256 and P-384 performance, I already have a solution for that too.

**Pull request closed without merging**
