### PR TITLE
Add SeededFixedRandom

### PR DESCRIPTION
**Pull request by eoger**
Somewhat related to #661, this adds a fake rng initialized with a seed that always holds the same results. I used the LFSR algorithm since it's pretty concise.

### CODE REVIEW

**Comment by briansmith** [comment]
I understand that you wrote this because you are writing tests. Did you see the test support code in https://briansmith.org/rustdoc/ring/test/rand/index.html? I would expect that the existing stuff, especially `FixedSliceSequenceRandom`, would be sufficient for almost all tests, since they are what I use for the NIST-supplied test vectors and similar.

I'd rather avoid adding any implementation of `SecureRandom` that isn't obviously only useful for tests like `FixedSliceSequenceRandom` since the purpose of `SecureRandom` is to ensure the output is not predictable even by the application using it.

For SGX and for other reasons we'll likely add a secure DRBG that takes a seed and that can be augmented with more seed material (reseeded). I don't know which one we would pick--probably HMAC-DRBG.

**Comment by eoger** [comment]
I tried using `FixedSliceSequenceRandom` with `EphemeralPrivateKey::generate()` but it's a bit harder since the way we get these random slices are not trivial: https://github.com/briansmith/ring/blob/9814ac47dff08424dd75e31881e7ba257880a096/src/ec/suite_b/private_key.rs#L62-L68

**Comment by briansmith** [comment]
> I tried using FixedSliceSequenceRandom with EphemeralPrivateKey::generate() but it's a bit harder since the way we get these random slices is not trivial:

In the case of P-256 ECDH, you need one 32-byte value per key generation as long as the value isn't "too big". In practice it is actually kind of difficult to make a "too big" value so almost any value will work. In particular, any 32-byte value where the high-order bit isn't set will work.

**Comment by eoger** [comment]
I've made it work with your suggestions, thank you! Closing this for now.

**Pull request closed without merging**
