### PR TITLE
change the comment type in `features!`'s matcher

### PR DESCRIPTION
**Pull request by zjp-CN**
This **might not** help to resolve https://github.com/briansmith/ring/issues/1469.

No idea for me :)

**Edit: please ignore what I explained here before.**

### CODE REVIEW

**Comment by zjp-CN** [comment]
@sdroege Yeah, it's already [there](https://github.com/rust-lang/rust/issues/95267).

**Comment by zjp-CN** [comment]
See
- https://github.com/rust-lang/rust/issues/95267#issuecomment-1078715011
- https://github.com/rust-lang/rust/commit/10644e0789a3c722e11f74968f24c1382f9ccb11

**Comment by faern** [comment]
Is the plan to have this merged and released no matter what `rustc` decides to do? It feels like the comment in question should not be a doc comment.

**Comment by paolobarbolini** [comment]
This should be merged anyway, even if the rustc regression were to be fixed. See https://github.com/rust-lang/rust/pull/95390#issuecomment-1080526970

**Review by briansmith — APPROVED** [review]

**Comment by briansmith** [comment]
Even though the rust-lang/rust change was made, which makes this non-critical, I've approved this change and I'll merge it as soon as CI/CD psases.

**Pull request merged**
