### PR TITLE
Fix compilation on DragonFly

### PR DESCRIPTION
**Pull request by mneumann**
Use /dev/urandom on DragonFly as well.

### CODE REVIEW

**Comment by briansmith** [comment]
@mneumann From either a Linux or Windows host, how can I test this in a DragonFly VM? Could you write a script that creates the necessary environment?

**Comment by mneumann** [comment]
@briansmith Sorry for the delay. Just try to compile master on DragonFly and it will fail to compile. Note that these two patches have been created independently from myself (or maybe I sent them to the list, I don't remember) in the official DragonFly ports repository to make [Zola](https://getzola.org) work:

https://github.com/DragonFlyBSD/DPorts/tree/master/www/zola/dragonfly

You see the two patch files at the top there, patching ring.

**Comment by mneumann** [comment]
@briansmith To test this, basically you just need to install rust on DragonFly (`pkg ins rust`). Then fetch the ring repo and do `cargo build`.

**Comment by mneumann** [comment]
@briansmith did you get any chance to test this?

**Comment by briansmith** [comment]
@mneumann Please review and test PR #1119. If it works then rebase this on top of that PR and I'll merge it.

**Comment by mneumann** [comment]
I create a new PR which works on top of #1119. Rebase was not possible, as in the meanwhile I deleted my git repo. Closing this issue in favor of #1134 .

**Pull request closed without merging**
