### PR TITLE
Improve Travis CI Android Builds

### PR DESCRIPTION
**Pull request by pietro**
This PR improves the Android situation on Travis CI. It caches some of the Android things we need to download for every build and adds AArch64 builds. It fixes both #486 and the issue I wrote about on [#518](https://github.com/briansmith/ring/issues/518#issuecomment-304114391).

### CODE REVIEW

**Comment by cedenday** [comment]
Can't find anything malicious in the changes.

**Comment by briansmith** [comment]
Thanks a ton for this!

I rebased these changes and pushed them (otherwise unmodified) to master:

52c645b7a006d3cecba50871ec42ce2109daab78 Don't install unnecessary packages on Travis CI Android builds.
b7073f4177cf87859b1d45950c5afca9f0b16ced Cache Android NDK, tools and platform tools on Travis CI.
06da374f661df435abbc216f554da38e49d47e4f Add support to install different Android system images on Travis CI.
759f1cc51fe5f5112066b0bb482514eea988bca0 Define Android API level needed for AArch64.
cd011b39e3a9e75885473a2b51661e41e2c9974f Add AArch64 to Travis CI builds.
ffe7e973b76a15cab783802f8d3c98992b8233d7 Use `travis_wait` on all Android release builds on Travis CI.
4388505aa500b9ed3521b410f73ac622022f8191 Add AArch64 build info to README.

**Comment by pietro** [comment]
Cool! Hopefully next week I'll have time to debug the 32-bit ARM issues when using clang.

**Comment by briansmith** [comment]
@pietro After this change some builds are failing with "No space left on device": https://travis-ci.org/briansmith/ring/jobs/240986948

**Comment by briansmith** [comment]
@pietro I had to revert these changes due to the build failures. Not sure what we can do. Maybe we can delete intermediate inputs after the input has been used and is no longer needed. And/or maybe when we need to rebuild a cached file, we should delete all the prevously- (stale) cached files before attempting the rebuild?

**Comment by briansmith** [comment]
I'm going to close this PR in favor of switching to `cross` for building and testing Android. Thanks for all your contributions here!

**Pull request closed without merging**
