### PR TITLE
Remove '#define asm __asm__' everywhere

### PR DESCRIPTION
**Pull request by frewsxcv**
Closes https://github.com/briansmith/ring/issues/69

I agree to license my contributions to each file under the same terms
given at the top of each file I changed.

### CODE REVIEW

**Comment by frewsxcv** [comment]
Addressed your comments

**Comment by briansmith** [comment]
I merged the crypto/bn part in 2ed6c664fe255453965044f83871e1e0860a346e.

It was my mistake to ask you to reformat the patch. Once that happened, I couldn't review it in any useful way. So, I went back and un-reformatted it and then reformatted it according to how I think the BoringSSL people prefer to have it.

I dropped the changes to crypto/modes/internal.h because all the inline asm in that file is going to get deleted anyway in your other pull request.

**Comment by briansmith** [comment]
Also, thanks!

**Comment by frewsxcv** [comment]
:+1:

**Pull request closed without merging**
