### PR TITLE
Add support for LoongArch64

### PR DESCRIPTION
**Pull request by heiher**
Follow up https://github.com/briansmith/ring/pull/1565

### CODE REVIEW

**Review by briansmith — APPROVED** [review]

**Review by briansmith — CHANGES_REQUESTED** [review]
@heiher The stuff in `base.h` is now to be in `target.h`. Note that the `clippy` job failed; try `mk/clippy.sh`. Please rebase on the main branch and resubmit.

**Comment by briansmith** [comment]
Is there no QEMU support for this target? Could you please add the rest of the stuff like the other targets have for QEMU to cargo.sh and install-build-tools.sh? This makes it very easy for us to all test this target manually, even if we don't add it to CI.

**Comment by briansmith** [comment]
I couldn't find the toolchain support in Ubuntu 22.04. Please help Ubuntu get your cross-compilation and QEMU support into Ubuntu if you haven't already. Thanks!

**Comment by heiher** [comment]
You're right. Fortunately, Debian/LoongArch port is already in progress. Thanks!

**Pull request merged**
