### PR TITLE
Add mipsel to Travis CI setup

### PR DESCRIPTION
**Pull request by LinusU**
Hopefully, this will help us to get closer to #562 

I've upgraded everything to xenial since it's the first LTS release to add the `gcc-mipsel-linux-gnu` package.

I chose `mipsel` because that's what I'm using, and I have an immediate need to get ring working on the [Omega2 - Onion](https://onion.io/omega2/) card.

I'm not expecting the CI to work on the first try so this will likely be a long process for me 😁 😴 🐎

### CODE REVIEW

**Comment by LinusU** [comment]
Hmm, can't really figure out what's going wrong here, it seems like it's having problems running the output binaries:

```text
     Running `/home/travis/build/briansmith/ring/target/aarch64-unknown-linux-gnu/debug/deps/ring-19165cbf4fcdcaf6`
/home/travis/build/briansmith/ring/target/aarch64-unknown-linux-gnu/debug/deps/ring-19165cbf4fcdcaf6: 1: /home/travis/build/briansmith/ring/target/aarch64-unknown-linux-gnu/debug/deps/ring-19165cbf4fcdcaf6: ELF�8h@h��@8: not found
/home/travis/build/briansmith/ring/target/aarch64-unknown-linux-gnu/debug/deps/ring-19165cbf4fcdcaf6: 2: /home/travis/build/briansmith/ring/target/aarch64-unknown-linux-gnu/debug/deps/ring-19165cbf4fcdcaf6: Syntax error: ")" unexpected
```

```text
     Running `/home/travis/build/briansmith/ring/target/arm-unknown-linux-gnueabihf/debug/deps/ring-b69869d80853b8b8`
/home/travis/build/briansmith/ring/target/arm-unknown-linux-gnueabihf/debug/deps/ring-b69869d80853b8b8: 1: /home/travis/build/briansmith/ring/target/arm-unknown-linux-gnueabihf/debug/deps/ring-b69869d80853b8b8: Syntax error: word unexpected (expecting ")")
```

I'm guessing that the problem is that it's trying to run the binary directly on the Travis machine, and not in qemu 🤔 

@briansmith any pointers on what could have gone wrong here? ☺️

**Comment by pietro** [comment]
> I'm guessing that the problem is that it's trying to run the binary directly on the Travis machine, and not in qemu

You removed the code that installs qemu for arm/aarch64 from travis.sh.

**Comment by LinusU** [comment]
😂 🤦‍♂️ I'm an idiot, I removed it from `travis.sh` since they aren't in a PPA, but rather in the main repo, and added them to the packages section. Only I never ran the script to regenerate the `.travis.yml` file 😄 

Still, I would have expected a different error, it threw me off 🤔 ☺️

**Comment by LinusU** [comment]
> qemu: Unsupported syscall: 278

I _think_ that this was probably added in Qemu 2.5, since it got downgraded from 2.5 to 2.4 because of my changes. Will look into this soon ☺️

**Comment by pietro** [comment]
Yeah, that's `getrandom()`. IMHO that's ok because of the /dev/urandom fallback. But that's @briansmith's call.

**Comment by LinusU** [comment]
@pietro _if_ we would use the `/dev/urandom` fallback, how do we actually tell the program to use that so that the tests don't fail? 🤔

**Comment by pietro** [comment]
The fallback is a default feature in ring. See the note at https://briansmith.org/rustdoc/ring/

I'm not sure why the tests are failing. i think the unsupported syscall error is a red herring. Other tests that pass have error too. Can you try using xenial only for mips and keep trusty for the other builds?

**Comment by briansmith** [comment]
What version of QEMU is `cross` using?

**Comment by LinusU** [comment]
Actually, the tests aren't failing 😄 

The only problem is that coveralls complains that the coverage have decreased by `-0.06%` 😂 

The only tests that are failing on Travis are the `mipsel` tests (because it's not implemented yet)

> What version of QEMU is `cross` using?

Depending on which target: `2.7.1`, `2.8.0` or `2.10`

@briansmith can we merge this and then open more PR to make progress on the mipsel port, or do you want me to work on the mipsel support in this branch?

**Comment by briansmith** [comment]
> @briansmith can we merge this and then open more PR to make progress on the mipsel port, or do you want me to work on the mipsel support in this branch?

Definitely I would prefer to have these changes separate from the rest of the MIPS work. I'll ask some questions in the MIPS issue.

**Comment by briansmith** [comment]
I am making substantial progress towards getting MIPS working and I plan to work towards integrating these CI changes once that initial progress has been completed.

**Comment by LinusU** [comment]
That's great, let me know if you want anything from me 🙌

**Comment by xen0n** [comment]
Hi, how's everything going regarding the MIPS porting work? I believe people are still interested. If not for Real Life™️ reasons I'd even personally do some of this work...

**Comment by briansmith** [comment]
I updated the base branch of this PR to "main" so I can remove "master".

What do you think about limiting this to clang only, and removing the GCC stuff? I think there are too many CI/CD jobs already.

**Comment by briansmith** [comment]
I had to move away from Travis CI to GitHub Actions. When I did the GitHub Actions rewrite, I learned quite a bit about how qemu-user works. This PR, except for being based on the old Travis-based CI, seems pretty close to what I think we should be doing in GitHub Actions. Are you still interested in this, enough to redo it for GitHub Actions? If so, I'll be watching for an update to this PR. Otherwise, we can close this.

**Comment by LinusU** [comment]
> Are you still interested in this, enough to redo it for GitHub Actions? 

Hopefully I should be able to do this after work today 🎉

**Comment by briansmith** [comment]
Closing this in favor of your other PR, #1120. Thanks!

**Pull request closed without merging**
