### PR TITLE
Add a simple Drop for aead::Key

### PR DESCRIPTION
**Pull request by jaysonsantos**
I saw this TODO and decided to implement it. Just let me know if that is what you were thinking about.

### CODE REVIEW

**Comment by briansmith** [comment]
Hi. Thank you very much for looking at the code and submitting this PR.

 I wrote that TODO very early in the *ring* project and I've made a lot of progress in our thinking regarding zeroization since then. Off-and-on I am working on documenting if/why/how we should do zeroization in *ring*, but it will be a while before that write-up is ready. In the meantime we're going to hold off on zeroization while we focus on the oxidation effort and other code cleanup. With that in mind, I committed d020ba9511156c1abe9971d98af708de502f5131 to remove the TODO comment so nobody else gets misled by it.

Thanks again for the PR though. Feel free to email me (brian@briansmith.org) if you want to chat about other changes that would be appropriate for the current efforts.

**Comment by jaysonsantos** [comment]
Hey @briansmith thanks for your response. Do you have plans to add memory lock? Should I file an issue for wishes?

**Comment by jaysonsantos** [comment]
Ah, taking advantage of this channel for communication. Reading the docs/code I found a bit hard to know how to do simple encryption/decryption stuff because I don't know much about encryption. If you have plans to add more descriptive docs let me know, maybe I could also help with what I figured out reading/debugging the code trying to figure out which Unspecified error happened :D.

**Comment by briansmith** [comment]
>  Do you have plans to add memory lock? 

I think it should probably be done as a custom allocator. Then we can consider adding support for custom allocators and then get that for free.

**Comment by briansmith** [comment]
> Reading the docs/code I found a bit hard to know how to do simple encryption/decryption stuff because I don't know much about encryption. If you have plans to add more descriptive docs let me know, maybe I could also help with what I figured out reading/debugging the code.

That would be great. See https://github.com/briansmith/ring/issues/418.

**Pull request closed without merging**
