### PR TITLE
Export ring::signature::ECDSASigning

### PR DESCRIPTION
**Pull request by tarcieri**
Exports `ec::suite_b::ecdsa::signing::Algorithm` as `ring::signature::ECDSASigning` to match a similar export for `ECDSAVerification`.

### CODE REVIEW

**Comment by briansmith** [comment]
I think we exported the ECDSA verification algorithm type due to a limitation in how Rust's type/visibility system works or perhaps due to a misunderstanding of it. We have `signature::SigningAlgorithm` which I expected to work for every use case. Can you use `signature::SigningAlgorithm` instead?

**Comment by tarcieri** [comment]
In this particular case I was trying to store it in a struct. I actually ended up avoiding that

**Comment by briansmith** [comment]
> In this particular case I was trying to store it in a struct. I actually ended up avoiding that

You can store a reference to the algorithm in a struct. It should be easy to do because `SigningAlgorithm: 'static`.

**Comment by tarcieri** [comment]
Ran into this again. I'd like to pass the signing algorithm to use as a parameter to a method which in turn calls `ECDSAKeyPair::from_pkcs8()`.

**Comment by briansmith** [comment]
> I'm not sure how I'd do that with SigningAlgorithm? The from_pkcs8() method concretely wants a &'static ring::ec::suite_b::ecdsa::signing::Algorithm.

Use `ring::signature::key_pair_from_pkcs8()`.

**Comment by tarcieri** [comment]
Aha, thanks

**Pull request closed without merging**
